//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pineapler.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualOrc.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;XRSDKOpenVR&quot;,
        ///  &quot;version&quot;: &quot;1.0.0-preview.1&quot;,
        ///  &quot;libraryName&quot;: &quot;XRSDKOpenVR&quot;,
        ///
        ///  &quot;displays&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;OpenVR Display&quot;
        ///    }
        ///  ],
        ///  &quot;inputs&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;OpenVR Input&quot;,
        ///      &quot;disablesLegacyInput&quot;: true,
        ///      &quot;disablesLegacyVr&quot; : true
        ///    }
        ///  ]
        ///}
        ///.
        /// </summary>
        internal static string UnitySubsystemsManifest {
            get {
                return ResourceManager.GetString("UnitySubsystemsManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;vr&quot;,
        ///    &quot;maps&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;head&quot;,
        ///            &quot;id&quot;: &quot;687bd32b-1837-4927-bec9-1a5005bffada&quot;,
        ///            &quot;actions&quot;: [
        ///                {
        ///                    &quot;name&quot;: &quot;position&quot;,
        ///                    &quot;type&quot;: &quot;Value&quot;,
        ///                    &quot;id&quot;: &quot;b4398d7c-1996-4044-8bb3-af58198fc0e9&quot;,
        ///                    &quot;expectedControlType&quot;: &quot;Vector3&quot;,
        ///                    &quot;processors&quot;: &quot;&quot;,
        ///                    &quot;interactions&quot;: &quot;&quot;,
        ///                    &quot;initialStateCheck&quot;: true
        ///                }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vr_inputs {
            get {
                return ResourceManager.GetString("vr_inputs", resourceCulture);
            }
        }
    }
}
